'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type BitButtonCustomEvent } from "@bitbox-ui/web";
import { BitButton as BitButtonElement, defineCustomElement as defineBitButton } from "@bitbox-ui/web/dist/components/bit-button.js";
import { BitCardTitle as BitCardTitleElement, defineCustomElement as defineBitCardTitle } from "@bitbox-ui/web/dist/components/bit-card-title.js";
import { BitCard as BitCardElement, defineCustomElement as defineBitCard } from "@bitbox-ui/web/dist/components/bit-card.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type BitButtonEvents = { onClick: EventName<BitButtonCustomEvent<MouseEvent>> };

export const BitButton: StencilReactComponent<BitButtonElement, BitButtonEvents> = /*@__PURE__*/ createComponent<BitButtonElement, BitButtonEvents>({
    tagName: 'bit-button',
    elementClass: BitButtonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onClick: 'click' } as BitButtonEvents,
    defineCustomElement: defineBitButton
});

type BitCardEvents = NonNullable<unknown>;

export const BitCard: StencilReactComponent<BitCardElement, BitCardEvents> = /*@__PURE__*/ createComponent<BitCardElement, BitCardEvents>({
    tagName: 'bit-card',
    elementClass: BitCardElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as BitCardEvents,
    defineCustomElement: defineBitCard
});

type BitCardTitleEvents = NonNullable<unknown>;

export const BitCardTitle: StencilReactComponent<BitCardTitleElement, BitCardTitleEvents> = /*@__PURE__*/ createComponent<BitCardTitleElement, BitCardTitleEvents>({
    tagName: 'bit-card-title',
    elementClass: BitCardTitleElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as BitCardTitleEvents,
    defineCustomElement: defineBitCardTitle
});
